### PR TITLE
feat: Add jgit dynamic version to jgit property source

### LINKED ISSUE #9: Add support for dynamic versioning (and possibly Maven CI Friendly)
Other langauges and build systems have something called dynamic versioning which means that the project version can be left out in the project configuration file (here: pom.xml) and instead the version is set dynamically based on tag in git repo. It the current comment does not have tag with valid semantic version then the nearest is found and the number of commits to that commit from HEAD will be build number.

Due to a limitation in Maven the current "solution" of MojoHaus Versions Maven plugin [goal](https://www.mojohaus.org/versions/versions-maven-plugin/use-dynamic-version-from-scm-mojo.html) does not work. @cstamas described it [here](https://issues.apache.org/jira/browse/MINSTALL-202) and as a the idea is to migrate the  MojoHaus Versions Plugin goal to [nisse](https://github.com/maveniverse/nisse) as core extension.

The current goal has few [optional parameters](https://www.mojohaus.org/versions/versions-maven-plugin/use-dynamic-version-from-scm-mojo.html#optional-parameters): 

* appendSnapshot: Whether the SNAPSHOT qualifier shall be apppended or not. Default: true
* defaultVersion: The default version used when SCM repository has no commit or no version tag. 
* propertyName: The name of the property that will contain the resolved version. Default: revisionUser 
* useVersion: Use this version instead of resolving from SCM tag information.

I'm currently not sure how configuration can be made for a core extension. Any input here would be appreciated.

Also, I'm not sure if there is any benefit of using ${revision} as [Maven CI Friendly](https://maven.apache.org/maven-ci-friendly.html).

### PR DESCRIPTION
**Pull request by cstamas**
Ingest PR #18 and add IT. By default new feat is not enabled, it needs to be explicitly enabled.

Fixes #9

### CODE REVIEW

**Comment by cstamas** [comment]
IT is ok.

@lfvjimisola pls take a look, if OK I can release

**Comment by jimisola** [comment]
> IT is ok.
> 
> @lfvjimisola pls take a look, if OK I can release

Not sure if you saw that there were a couple of more IT for dynamic versioning in the Mojohaus version. Those ITs tests the different conditions in the (appendSnapshot, useVersion etc).

**Comment by cstamas** [comment]
@lfvjimisola can you point me at those?

**Comment by jimisola** [comment]
> IT is ok.
> 
> @lfvjimisola pls take a look, if OK I can release

Sure. I got some instant feedback on my code as I was not aware of VersionScheme and you streams was much more elegant.

You wrote "By default new feat is not enabled, it needs to be explicitly enabled.". It's not obvious for me how I do that.

**Comment by cstamas** [comment]
ITs ported. But one fails: it-dynamic-versioning-scm-tag-4-commits-1-vtag: it adds 3 commits but expects `1.1.2-4-SNAPSHOT`?

As IT does: .mvn/maven.conf
```
-D
nisse.source.jgit.dynamicVersion=true
```

**Comment by cstamas** [comment]
IT failure:
```
[INFO]   java.lang.AssertionError: Expected version '1.1.2-4-SNAPSHOT', but found '1.1.2-3-SNAPSHOT'. Expression: (actualVersion == expectedVersion). Values: actualVersion = 1.1.2-3-SNAPSHOT, expectedVersion = 1.1.2-4-SNAPSHOT
[INFO]           it-dynamic-versioning-scm-tag-4-commits-1-vtag/pom.xml FAILED (1.634 s)
```

**Comment by jimisola** [comment]
> nisse.source.jgit.dynamicVersion=true

Forgot about that. That is correct. There was a minor change in how the buildno qualifier is calculated (count++ was moved).

**Comment by cstamas** [comment]
So `1.1.2-3-SNAPSHOT` is the expected and correct value?

**Comment by jimisola** [comment]
> So `1.1.2-3-SNAPSHOT` is the expected and correct value?

A bit tired here (and recovering from a man cold). But, yes. The buildno was always >= 2 otherwise.

Compare:

  https://github.com/maveniverse/nisse/pull/20/files#diff-ebb795855e7b56bff39052437cc5ea03133c3b2ce39cfe1fbb2ed21f4b244a9bR202
  
  with

https://github.com/mojohaus/versions/blob/master/versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DynamicVersioningSCMPlugin.java#L178

**Comment by cstamas** [comment]
If this CI gets green am merging this. Are you ok? Can I release? Will do 0.3.0 if you are ok with it.

**Comment by jimisola** [comment]
> If this CI gets green am merging this. Are you ok? Can I release? Will do 0.3.0 if you are ok with it.
> 
> Note: meanwhile it did get green 😄

I'm ok. Thanks for asking. Downhill now.

I've done some manual testing as well. Not all cases but IWFM

**Comment by cstamas** [comment]
we can always do 0.3.1 :smile: am merging this, want to fix some other issue as well (plugin G) and will release

**Comment by jimisola** [comment]
Great thanks. Plugin G?

Have prepared everything at our end so will hopefully be able to try it all out tomorrow. Ideally, no 0.3.1 ;)

**Comment by jimisola** [comment]
Is any documention of this feature needed? It mimics with some Java stuff (such as -SNAPSHOT:

* https://github.com/ofek/hatch-vcs
* https://github.com/mtkennerly/poetry-dynamic-versioning

**Comment by cstamas** [comment]
@lfvjimisola PRs welcome :smile: I think it would be good thing to have it documented.

**Comment by jimisola** [comment]
> PR accepted. In the meantime tried to release but sonatype rejected my staging attempt.
> 
> 0.3.1-SNAPSHOT deployed to https://s01.oss.sonatype.org/content/repositories/snapshots/ and opened a support ticket with Sonatype why is my deploy failed.

Can it be because of VersionInformation.java and that it's from MojoHaus with MIT license?

**Comment by jimisola** [comment]
> @lfvjimisola PRs welcome 😄 I think it would be good thing to have it documented.

I'll see what I can do, but it'll probably have to be next week.

**Comment by cstamas** [comment]
No, for sure is not that the reason.
Simply, s01.oss.sonatype.org _refuse_ my deploy attempt, while today I did deploy to Central new maveniverse parent 20.... unsure what is happening.

Sonatype support tickets are sadly not public, they use zendesk if am not wrong.

**Comment by jimisola** [comment]
Fingers crossed that you get a quick response.

**Comment by cstamas** [comment]
@darthhater is on the thing already, so...

**Comment by cstamas** [comment]
0.3.0 released, sync to central pending...

**Comment by cstamas** [comment]
It landed on central. Please test and provide some feedback!

**Comment by jimisola** [comment]
An even better option from a user perspective would of course be if a temp file was used.

**Comment by cstamas** [comment]
Yes, this POM is the "inlined POM" needed for maven3 (mvn4 has means to do this cleanly)

**Comment by cstamas** [comment]
Created https://github.com/maveniverse/nisse/issues/21

**Pull request merged**
